#!/usr/bin/env bash
# 
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Simple tool to deploy multiple Anthos clusters with ASM, ACM, and 
# various demo scenarios configured
# TODO - Apigee/Endpoints
#      - mTLS by default for ASM
#      - bookinfo deploy with SLO/SLI configs (new addon that requires ASM)

# valid options[cleanup|deploy]
ACTION=$1

function prep {
  source cfg/default.config

  # set gcloud variables
  echo "$FUNCNAME: Setting gcloud information Project and Region"
  gcloud config set project $PROJECT 
  gcloud config set compute/zone $REGION

  # Setting a few additional variables
  echo "$FUNCNAME: Setting additional variables"
  PROJECT_NUMBER=$(gcloud projects describe $PROJECT --format="value(projectNumber)")
  WORKLOAD_POOL=$PROJECT.svc.id.goog
  MESH_ID="proj-$PROJECT_NUMBER"
  REPO_NAME=anthos-lab-acm
  REPO_DIR=$HOME/$REPO_NAME
  DEPLOY_DIR=$PWD/deploy
  ADDONS_DIR=$PWD/addons

  # Read in cluster list
  echo "$FUNCNAME: Reading in cluster list"
  CLUSTERS=$(<$CLUSTER_LIST)
  for cluster in ${CLUSTERS[@]}
  do
    echo "Cluster: $cluster"
  done
}

function action {
  # if it's a deploy, we start with Anthos
  if [ $ACTION == 'deploy' ];then
    source $ADDONS_DIR/anthos/$ACTION.sh
  fi
  # then apply the addons, or clean them up first
  for addon in ${ADDONS[@]};do
    source $ADDONS_DIR/$addon/$ACTION.sh
  done
  # if it's a cleanup, we clean up Anthos last
  if [ $ACTION == 'cleanup' ];then
    source $ADDONS_DIR/anthos/$ACTION.sh
  fi
}

case $ACTION in
  deploy|cleanup) 
    prep
    action
  ;;

  *)
    echo "USAGE: $0 [cleanup|deploy]"
  ;;
esac
