#!/bin/bash
# 
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Simple tool to deploy multiple Anthos clusters with ASM, ACM, and 
# various demo scenarios configured
# TODO - Apigee/Endpoints
#      - mTLS by default for ASM
#      - bookinfo deploy with SLO/SLI configs (new addon that requires ASM)

# valid options[cleanup|deploy]
# the option is defined in $ACTION - which is set when the container 
# is started by the docker command.
# 
# additional options and configuration parmeters are set in the default.config # file that is also passed into the container via an --env-file option 

# header color 
HC='\033[0;32m'
# output color
OC='\033[0;34m'
# error color
EC='\033[1;31m'
# turn off forced color
NC='\033[0m'

function prep {

  # authenticate via service account
  echo -e "\n\n${HC}------------------- GCLOUD CONFIGURATION --------------------${NC}\n"
  echo -e "${OC}  * Logging in with Service Account anthos-lab-sa${NC}"
  gcloud auth activate-service-account --key-file=/opt/anthos-lab-sa.json

  # set gcloud variables
  echo -e "${OC}  * Setting Project and Region ${NC}"
  gcloud config set project $PROJECT 
  gcloud config set compute/zone $REGION

  # Setting a few additional variables
  echo -e "${OC}  * Setting additional variables ${NC}"
  PROJECT_NUMBER=$(gcloud projects describe $PROJECT --format="value(projectNumber)")
  WORKLOAD_POOL=$PROJECT.svc.id.goog
  MESH_ID="proj-$PROJECT_NUMBER"
  DEPLOY_DIR=$PWD/deploy
  ADDONS_DIR=$PWD/addons

  echo -e "${OC}  * Lab Prep Complete. Moving on to $ACTION ${NC}"
}

function action {
  # if it's a deploy, we start with Anthos
  if [ $ACTION == 'deploy' ];then
    source $ADDONS_DIR/anthos/$ACTION.sh
  fi
  # then apply the addons, or clean them up first
  for addon in asm acm;do
    source $ADDONS_DIR/$addon/$ACTION.sh
  done
  # if it's a cleanup, we clean up Anthos last
  if [ $ACTION == 'cleanup' ];then
    source $ADDONS_DIR/anthos/$ACTION.sh
  fi
}

case $ACTION in
  deploy|cleanup) 
    prep
    action
  ;;

  *)
    echo "USAGE: $0 [cleanup|deploy]"
  ;;
esac
